### ISSUE TITLE
데이터 초기화 관련

### ISSUE THREAD

**Issue by HwangUiTaek** [TigerCompany-tigris/tigris-ai-platform#3]
데이터 초기화 부분이 최초 API 호출 시점으로 되어있어서
서버 기동 후 처음 API를 호출할때의 속도 저하를 가져오고 있습니다

데이터 초기화 시점이 서버 기동시로 변경되어야 할꺼 같습니다

**Comment by tigrison** [comment]
데이터 클래스 구현시 __init__에 초기화 로직 삽입하면 서버 기동시 초기화함
